version: '3.8'

services:
  keskonmange-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: keskonmange-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:20880:3001"
    env_file:
      - ./backend/.env.docker
    volumes:
      # Optionnel : pour persister les logs
      - ./logs:/app/logs
    networks:
      - keskonmange-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  keskonmange-network:
    driver: bridge

volumes:
  logs:
    driver: local
